/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright (c) 2026 B5-Software
 *
 * This file is part of Could I Be Your Partner.
 *
 * i18n core module — supports zh-CN (source), en, de.
 * Design principle: zh-CN is the identity/fallback; existing Chinese strings
 * are NEVER deleted or modified. Non-zh languages override via translation
 * maps keyed by string identifiers.
 */

const I18N_SUPPORTED_LANGUAGES = [
  { value: 'zh-CN', label: '简体中文' },
  { value: 'en',    label: 'English' },
  { value: 'de',    label: 'Deutsch' }
];

let _i18nLang = 'zh-CN';
let _i18nDict = {}; // active dictionary (empty for zh-CN → falls back to caller-provided default)

/**
 * Initialise i18n from saved settings. Called once at app startup.
 * @param {string} lang  Language code: 'zh-CN' | 'en' | 'de'
 */
function i18nInit(lang) {
  i18nSetLanguage(lang || 'zh-CN');
}

/**
 * Switch active language at runtime.
 * Dispatches a 'languagechange' CustomEvent on window so listeners can react.
 */
function i18nSetLanguage(lang) {
  if (!I18N_SUPPORTED_LANGUAGES.some(l => l.value === lang)) lang = 'zh-CN';
  _i18nLang = lang;
  _i18nDict = (lang === 'zh-CN') ? {} : (I18N_TRANSLATIONS[lang] || {});
  document.documentElement.lang = lang;
  window.dispatchEvent(new CustomEvent('languagechange', { detail: { lang } }));
}

function i18nGetLanguage() {
  return _i18nLang;
}

/**
 * Translate a key.
 * @param {string} key  Translation key (dotted path, e.g. 'ui.sidebar.chat')
 * @param {string} fallback  Original Chinese string to use when no translation found.
 * @param {object} [params]  { placeholder: value } for {placeholder} substitution.
 * @returns {string}  Translated string, or fallback if not found.
 */
function t(key, fallback, params) {
  if (!key || _i18nLang === 'zh-CN') {
    return params ? _i18nFill(fallback, params) : fallback;
  }
  let str = _i18nDict[key];
  if (str === undefined) {
    // Try nested lookup (dot notation)
    str = _i18nLookup(key);
  }
  if (str === undefined || str === null) {
    str = fallback;
  }
  return params ? _i18nFill(str, params) : str;
}

function _i18nLookup(key) {
  const parts = key.split('.');
  let obj = _i18nDict;
  for (const p of parts) {
    if (obj && typeof obj === 'object' && p in obj) {
      obj = obj[p];
    } else {
      return undefined;
    }
  }
  return typeof obj === 'string' ? obj : undefined;
}

function _i18nFill(str, params) {
  if (!params) return str;
  return str.replace(/\{(\w+)\}/g, (m, k) => (params[k] !== undefined ? String(params[k]) : m));
}

/**
 * Apply translations to all [data-i18n] elements in the DOM.
 * Call this after language change and after dynamic content insertion.
 * - data-i18n="key" → textContent
 * - data-i18n-placeholder="key" → placeholder
 * - data-i18n-title="key" → title attribute
 */
function i18nApplyToDOM(root) {
  const scope = root || document;
  // textContent
  scope.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const val = t(key, el.textContent);
    if (val) el.textContent = val;
  });
  // placeholder
  scope.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    const val = t(key, el.getAttribute('placeholder'));
    if (val) el.setAttribute('placeholder', val);
  });
  // title
  scope.querySelectorAll('[data-i18n-title]').forEach(el => {
    const key = el.getAttribute('data-i18n-title');
    const val = t(key, el.getAttribute('title'));
    if (val) el.setAttribute('title', val);
  });
}

// ── Translation dictionaries (populated by language files) ──
const I18N_TRANSLATIONS = {};

/**
 * Register a translation dictionary for a language.
 * Called by en.js / de.js at load time.
 */
function i18nRegister(lang, dict) {
  I18N_TRANSLATIONS[lang] = dict;
  // If this is the active language, refresh the dict reference
  if (_i18nLang === lang) {
    _i18nDict = dict || {};
    i18nApplyToDOM();
  }
}

// ── System prompt & tool description translation helpers ──

/**
 * Returns the localized system prompt for the given mode.
 * Falls back to the caller's original (Chinese) prompt if no translation exists.
 * @param {string} mode  'chat' | 'code' | 'babe'
 * @param {string} fallbackPrompt  The original Chinese prompt generated by the caller.
 * @param {object} [params]  Parameters for prompt template interpolation.
 * @returns {string}
 */
function i18nGetSystemPrompt(mode, fallbackPrompt, params) {
  if (_i18nLang === 'zh-CN') return fallbackPrompt;
  const prompts = _i18nDict._systemPrompts;
  if (prompts && prompts[mode]) {
    const val = prompts[mode];
    return typeof val === 'function' ? val(params || {}) : val;
  }
  return fallbackPrompt;
}

/**
 * Returns the localized description for a tool.
 * Falls back to the original Chinese desc if no translation exists.
 * @param {string} toolName  Tool identifier (e.g. 'readFile')
 * @param {string} fallbackDesc  Original Chinese description
 * @returns {string}
 */
function i18nGetToolDesc(toolName, fallbackDesc) {
  if (_i18nLang === 'zh-CN') return fallbackDesc;
  const tools = _i18nDict._tools;
  if (tools && tools[toolName]) return tools[toolName];
  return fallbackDesc;
}

/**
 * Returns the localized tool schema description.
 * Falls back to the original Chinese description if no translation exists.
 * @param {string} toolName
 * @param {string} fallbackDesc  Original Chinese schema description
 * @returns {string}
 */
function i18nGetToolSchemaDesc(toolName, fallbackDesc) {
  if (_i18nLang === 'zh-CN') return fallbackDesc;
  const schemas = _i18nDict._toolSchemas;
  if (schemas && schemas[toolName]) return schemas[toolName];
  return fallbackDesc;
}

/**
 * Returns the localized category label.
 * @param {string} category  Original Chinese category (e.g. '娱乐')
 * @param {string} fallback
 * @returns {string}
 */
function i18nGetCategory(category, fallback) {
  if (_i18nLang === 'zh-CN') return fallback || category;
  const cats = _i18nDict._categories;
  if (cats && cats[category]) return cats[category];
  return fallback || category;
}

/**
 * Returns a localized tool return / error message.
 * @param {string} key  Key in _toolReturns (e.g. 'file_not_exists')
 * @param {string} fallback  Original Chinese message
 * @param {object} [params]  Placeholder values
 * @returns {string}
 */
function i18nToolReturn(key, fallback, params) {
  if (_i18nLang === 'zh-CN' || !key) {
    return params ? _i18nFill(fallback, params) : fallback;
  }
  const returns = _i18nDict._toolReturns;
  let str = returns && returns[key];
  if (str === undefined) str = fallback;
  return params ? _i18nFill(str, params) : str;
}

// Expose globally
window.i18nInit = i18nInit;
window.i18nSetLanguage = i18nSetLanguage;
window.i18nGetLanguage = i18nGetLanguage;
window.t = t;
window.i18nApplyToDOM = i18nApplyToDOM;
window.i18nRegister = i18nRegister;
window.i18nGetSystemPrompt = i18nGetSystemPrompt;
window.i18nGetToolDesc = i18nGetToolDesc;
window.i18nGetToolSchemaDesc = i18nGetToolSchemaDesc;
window.i18nGetCategory = i18nGetCategory;
window.i18nToolReturn = i18nToolReturn;
window.I18N_SUPPORTED_LANGUAGES = I18N_SUPPORTED_LANGUAGES;
