/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright (c) 2026 B5-Software
 *
 * This file is part of Could I Be Your Partner.
 */

// Tool definitions for the AI Agent
const TOOL_DEFINITIONS = [
  { name: 'getTarot', desc: '抽取塔罗牌', icon: 'fa-star', category: '娱乐', sensitive: false },
  { name: 'todoList', desc: '管理待办事项', icon: 'fa-list-check', category: '效率', sensitive: false },
  { name: 'runSubAgent', desc: '运行子代理', icon: 'fa-users', category: '代理', sensitive: false },
  { name: 'generateImage', desc: '生成图片', icon: 'fa-image', category: '创作', sensitive: false },
  { name: 'webSearch', desc: '后台Bing搜索', icon: 'fa-magnifying-glass', category: '网络', sensitive: false },
  { name: 'webFetch', desc: '获取网页数据', icon: 'fa-download', category: '网络', sensitive: true },
  { name: 'knowledgeBaseSearch', desc: '搜索知识库', icon: 'fa-database', category: '知识', sensitive: false },
  { name: 'knowledgeBaseAdd', desc: '添加知识', icon: 'fa-plus', category: '知识', sensitive: false },
  { name: 'knowledgeBaseDelete', desc: '删除知识', icon: 'fa-trash-can', category: '知识', sensitive: true },
  { name: 'knowledgeBaseUpdate', desc: '更新知识', icon: 'fa-pen', category: '知识', sensitive: false },
  { name: 'memorySearch', desc: '搜索记忆', icon: 'fa-brain', category: '记忆', sensitive: false },
  { name: 'memoryAdd', desc: '添加记忆', icon: 'fa-plus', category: '记忆', sensitive: false },
  { name: 'memoryDelete', desc: '删除记忆', icon: 'fa-trash-can', category: '记忆', sensitive: true },
  { name: 'memoryUpdate', desc: '更新记忆', icon: 'fa-pen', category: '记忆', sensitive: false },
  { name: 'localSearch', desc: '搜索本地文件', icon: 'fa-folder-open', category: '文件', sensitive: false },
  { name: 'readFile', desc: '读取文件', icon: 'fa-file', category: '文件', sensitive: false },
  { name: 'editFile', desc: '编辑文件', icon: 'fa-file-pen', category: '文件', sensitive: true },
  { name: 'createFile', desc: '创建文件', icon: 'fa-file-circle-plus', category: '文件', sensitive: false },
  { name: 'deleteFile', desc: '删除文件', icon: 'fa-file-circle-minus', category: '文件', sensitive: true },
  { name: 'moveFile', desc: '移动/重命名文件', icon: 'fa-file-export', category: '文件', sensitive: true },
  { name: 'copyFile', desc: '复制文件', icon: 'fa-copy', category: '文件', sensitive: false },
  { name: 'listDirectory', desc: '列出目录', icon: 'fa-folder', category: '文件', sensitive: false },
  { name: 'makeDirectory', desc: '创建目录', icon: 'fa-folder-plus', category: '文件', sensitive: false },
  { name: 'deleteDirectory', desc: '删除目录', icon: 'fa-folder-minus', category: '文件', sensitive: true },
  { name: 'runJavaScriptCode', desc: '运行JS代码', icon: 'fa-code', category: '代码', sensitive: false },
  { name: 'runNodeJavaScriptCode', desc: '运行JS代码(Node.js,需确认)', icon: 'fa-code', category: '代码', sensitive: true },
  { name: 'runShellScriptCode', desc: '运行Shell脚本', icon: 'fa-terminal', category: '代码', sensitive: true },
  { name: 'makeTerminal', desc: '创建终端', icon: 'fa-terminal', category: '终端', sensitive: false },
  { name: 'runTerminalCommand', desc: '执行终端命令', icon: 'fa-play', category: '终端', sensitive: true },
  { name: 'awaitTerminalCommand', desc: '等待终端命令', icon: 'fa-hourglass', category: '终端', sensitive: true },
  { name: 'killTerminal', desc: '关闭终端', icon: 'fa-xmark', category: '终端', sensitive: false },
  { name: 'readClipboard', desc: '读取剪贴板', icon: 'fa-clipboard', category: '系统', sensitive: false },
  { name: 'writeClipboard', desc: '写入剪贴板', icon: 'fa-paste', category: '系统', sensitive: false },
  { name: 'takeScreenshot', desc: '截取屏幕', icon: 'fa-camera', category: '系统', sensitive: false },
  { name: 'extractTextFromImage', desc: 'OCR文字识别', icon: 'fa-file-image', category: '系统', sensitive: false },
  { name: 'getSystemInfo', desc: '获取系统信息', icon: 'fa-computer', category: '系统', sensitive: false },
  { name: 'getNetworkStatus', desc: '获取网络状态', icon: 'fa-wifi', category: '系统', sensitive: false },
  { name: 'openBrowser', desc: '打开浏览器', icon: 'fa-globe', category: '系统', sensitive: false },
  { name: 'openFileExplorer', desc: '打开文件管理器', icon: 'fa-folder-open', category: '系统', sensitive: false },
  { name: 'manageContext', desc: '管理上下文', icon: 'fa-window-maximize', category: '代理', sensitive: false },
  { name: 'autoSummarizeContext', desc: '自动总结上下文', icon: 'fa-highlighter', category: '代理', sensitive: false },
  { name: 'listSkills', desc: '列出技能', icon: 'fa-lightbulb', category: '技能', sensitive: false },
  { name: 'makeSkill', desc: '创建技能', icon: 'fa-wand-magic-sparkles', category: '技能', sensitive: false },
  { name: 'updateSkill', desc: '更新技能', icon: 'fa-pen-to-square', category: '技能', sensitive: false },
  { name: 'initGeogebra', desc: '初始化Geogebra', icon: 'fa-chart-line', category: 'Geogebra', sensitive: false },
  { name: 'runGeogebraCommand', desc: '执行Geogebra命令（Classic仅1参数）', icon: 'fa-play', category: 'Geogebra', sensitive: false },
  { name: 'getFunctionsFromGeogebra', desc: '获取Geogebra对象列表', icon: 'fa-list', category: 'Geogebra', sensitive: false },
  { name: 'addFunctionToGeogebra', desc: '添加函数/对象（示例: f(x)=x^2-1）', icon: 'fa-plus', category: 'Geogebra', sensitive: false },
  { name: 'updateFunctionInGeogebra', desc: '更新函数（示例: f(x)=x^3-1）', icon: 'fa-pen', category: 'Geogebra', sensitive: false },
  { name: 'deleteFunctionFromGeogebra', desc: '删除对象（示例: f）', icon: 'fa-trash-can', category: 'Geogebra', sensitive: true },
  { name: 'getCurrentGraphFromGeogebra', desc: '导出当前图形（PNG）', icon: 'fa-image', category: 'Geogebra', sensitive: false },
  { name: 'getCurrentGraphDataFromGeogebra', desc: '获取对象/数值数据（如 Roots 返回的点需用 x(A)）', icon: 'fa-chart-bar', category: 'Geogebra', sensitive: false },
  { name: 'initCanvas', desc: '初始化画布', icon: 'fa-palette', category: '画布', sensitive: false },
  { name: 'clearCanvas', desc: '清空画布', icon: 'fa-eraser', category: '画布', sensitive: false },
  { name: 'addCanvasObject', desc: '添加画布对象（rect/circle/ellipse/line/polyline/polygon/path/text）', icon: 'fa-plus', category: '画布', sensitive: false },
  { name: 'updateCanvasObject', desc: '更新画布对象属性', icon: 'fa-pen', category: '画布', sensitive: false },
  { name: 'deleteCanvasObject', desc: '删除画布对象', icon: 'fa-trash-can', category: '画布', sensitive: false },
  { name: 'exportCanvasSVG', desc: '导出画布为SVG到工作区', icon: 'fa-file-export', category: '画布', sensitive: false },
  { name: 'askQuestions', desc: '询问用户问题收集信息', icon: 'fa-clipboard-question', category: '交互工具', sensitive: false },
  { name: 'downloadFile', desc: '从互联网下载文件到工作区', icon: 'fa-download', category: '网络工具', sensitive: true }
];

// Dangerous command keywords for different platforms/shells
const DANGEROUS_COMMANDS = {
  common: ['rm -rf', 'rmdir', 'del /f', 'format', 'mkfs', 'dd if=', 'chmod 777', ':(){:|:&};:', 'fork bomb', '> /dev/sda', 'shutdown', 'reboot', 'halt', 'poweroff', 'kill -9', 'killall', 'pkill'],
  windows: ['Remove-Item -Recurse -Force', 'Format-Volume', 'Clear-Disk', 'Stop-Process -Force', 'Remove-Partition', 'rd /s /q', 'reg delete', 'bcdedit', 'diskpart'],
  linux: ['rm -rf /', 'chmod -R 777 /', 'chown -R', 'mv /* /dev/null', 'wget.*|.*sh', 'curl.*|.*sh', 'crontab -r', 'iptables -F', 'systemctl stop', 'service.*stop'],
  macos: ['rm -rf /', 'diskutil eraseDisk', 'csrutil disable', 'nvram -c', 'bless --unbless']
};

// OpenAI-format tool schemas for LLM
function getToolSchemas(enabledTools) {
  const schemas = {
    getTarot: { type: 'function', function: { name: 'getTarot', description: '抽取一张塔罗牌（使用设置中配置的随机数源：CSPRNG软件随机或TRNG硬件真随机，调用后返回结果中entropySource字段会标明使用的随机数类型，在向用户解析塔罗牌时请标明随机数类型以增强可信度）', parameters: { type: 'object', properties: {}, required: [] } } },
    todoList: { type: 'function', function: { name: 'todoList', description: '管理待办事项列表', parameters: { type: 'object', properties: { action: { type: 'string', enum: ['add', 'remove', 'toggle', 'list'], description: '操作类型' }, text: { type: 'string', description: '待办事项内容' }, id: { type: 'number', description: '待办事项ID' } }, required: ['action'] } } },
    runSubAgent: { type: 'function', function: { name: 'runSubAgent', description: '运行子代理完成特定任务', parameters: { type: 'object', properties: { task: { type: 'string', description: '子代理要完成的任务' }, context: { type: 'string', description: '给子代理的上下文信息' } }, required: ['task'] } } },
    generateImage: { type: 'function', function: { name: 'generateImage', description: '根据文本提示生成图片', parameters: { type: 'object', properties: { prompt: { type: 'string', description: '图片描述(英文)' } }, required: ['prompt'] } } },
    webSearch: { type: 'function', function: { name: 'webSearch', description: '通过Bing搜索信息', parameters: { type: 'object', properties: { query: { type: 'string', description: '搜索关键词' } }, required: ['query'] } } },
    webFetch: { type: 'function', function: { name: 'webFetch', description: '获取网页内容', parameters: { type: 'object', properties: { url: { type: 'string', description: '网页URL' } }, required: ['url'] } } },
    knowledgeBaseSearch: { type: 'function', function: { name: 'knowledgeBaseSearch', description: '搜索知识库', parameters: { type: 'object', properties: { query: { type: 'string', description: '搜索关键词' } }, required: ['query'] } } },
    knowledgeBaseAdd: { type: 'function', function: { name: 'knowledgeBaseAdd', description: '向知识库添加信息', parameters: { type: 'object', properties: { title: { type: 'string', description: '标题' }, content: { type: 'string', description: '内容' } }, required: ['title', 'content'] } } },
    knowledgeBaseDelete: { type: 'function', function: { name: 'knowledgeBaseDelete', description: '从知识库删除信息', parameters: { type: 'object', properties: { id: { type: 'string', description: '知识条目ID' } }, required: ['id'] } } },
    knowledgeBaseUpdate: { type: 'function', function: { name: 'knowledgeBaseUpdate', description: '更新知识库信息', parameters: { type: 'object', properties: { id: { type: 'string', description: '知识条目ID' }, title: { type: 'string' }, content: { type: 'string' } }, required: ['id'] } } },
    memorySearch: { type: 'function', function: { name: 'memorySearch', description: '搜索长期记忆', parameters: { type: 'object', properties: { query: { type: 'string', description: '搜索关键词' } }, required: ['query'] } } },
    memoryAdd: { type: 'function', function: { name: 'memoryAdd', description: '添加长期记忆', parameters: { type: 'object', properties: { content: { type: 'string', description: '记忆内容' }, tags: { type: 'array', items: { type: 'string' }, description: '标签' } }, required: ['content'] } } },
    memoryDelete: { type: 'function', function: { name: 'memoryDelete', description: '删除长期记忆', parameters: { type: 'object', properties: { id: { type: 'string', description: '记忆ID' } }, required: ['id'] } } },
    memoryUpdate: { type: 'function', function: { name: 'memoryUpdate', description: '更新长期记忆', parameters: { type: 'object', properties: { id: { type: 'string', description: '记忆ID' }, content: { type: 'string' }, tags: { type: 'array', items: { type: 'string' } } }, required: ['id'] } } },
    localSearch: { type: 'function', function: { name: 'localSearch', description: '搜索本地文件和目录', parameters: { type: 'object', properties: { directory: { type: 'string', description: '搜索目录' }, pattern: { type: 'string', description: '搜索模式（支持通配符或正则表达式）' }, options: { type: 'object', properties: { ignoreCase: { type: 'boolean', description: '是否忽略大小写（默认true）' }, maxResults: { type: 'number', description: '最大结果数（默认200）' }, fileOnly: { type: 'boolean', description: '仅搜索文件' }, dirOnly: { type: 'boolean', description: '仅搜索目录' }, regex: { type: 'boolean', description: '使用正则表达式匹配' }, depth: { type: 'number', description: '搜索深度限制（-1表示无限制）' } }, description: '搜索选项' } }, required: ['directory', 'pattern'] } } },
    readFile: { type: 'function', function: { name: 'readFile', description: '读取文件内容', parameters: { type: 'object', properties: { path: { type: 'string', description: '文件路径' } }, required: ['path'] } } },
    editFile: { type: 'function', function: { name: 'editFile', description: '编辑文件', parameters: { type: 'object', properties: { path: { type: 'string', description: '文件路径' }, content: { type: 'string', description: '新内容' } }, required: ['path', 'content'] } } },
    createFile: { type: 'function', function: { name: 'createFile', description: '创建新文件', parameters: { type: 'object', properties: { path: { type: 'string', description: '文件路径' }, content: { type: 'string', description: '文件内容' } }, required: ['path'] } } },
    deleteFile: { type: 'function', function: { name: 'deleteFile', description: '删除文件', parameters: { type: 'object', properties: { path: { type: 'string', description: '文件路径' } }, required: ['path'] } } },
    moveFile: { type: 'function', function: { name: 'moveFile', description: '移动/重命名文件', parameters: { type: 'object', properties: { source: { type: 'string', description: '源路径' }, destination: { type: 'string', description: '目标路径' } }, required: ['source', 'destination'] } } },
    copyFile: { type: 'function', function: { name: 'copyFile', description: '复制文件', parameters: { type: 'object', properties: { source: { type: 'string', description: '源路径' }, destination: { type: 'string', description: '目标路径' } }, required: ['source', 'destination'] } } },
    listDirectory: { type: 'function', function: { name: 'listDirectory', description: '列出目录内容', parameters: { type: 'object', properties: { path: { type: 'string', description: '目录路径' } }, required: ['path'] } } },
    makeDirectory: { type: 'function', function: { name: 'makeDirectory', description: '创建目录', parameters: { type: 'object', properties: { path: { type: 'string', description: '目录路径' } }, required: ['path'] } } },
    deleteDirectory: { type: 'function', function: { name: 'deleteDirectory', description: '删除目录', parameters: { type: 'object', properties: { path: { type: 'string', description: '目录路径' } }, required: ['path'] } } },
    runJavaScriptCode: { type: 'function', function: { name: 'runJavaScriptCode', description: '运行JS代码(纯JS,无Node.js)', parameters: { type: 'object', properties: { code: { type: 'string', description: 'JavaScript代码' } }, required: ['code'] } } },
    runNodeJavaScriptCode: { type: 'function', function: { name: 'runNodeJavaScriptCode', description: '运行JS代码(Node.js环境,允许require等,需确认)', parameters: { type: 'object', properties: { code: { type: 'string', description: 'JavaScript代码' } }, required: ['code'] } } },
    runShellScriptCode: { type: 'function', function: { name: 'runShellScriptCode', description: '运行Shell脚本', parameters: { type: 'object', properties: { script: { type: 'string', description: 'Shell脚本内容' } }, required: ['script'] } } },
    makeTerminal: { type: 'function', function: { name: 'makeTerminal', description: '创建终端会话', parameters: { type: 'object', properties: {}, required: [] } } },
    runTerminalCommand: { type: 'function', function: { name: 'runTerminalCommand', description: '在终端执行命令', parameters: { type: 'object', properties: { terminalId: { type: 'number', description: '终端ID' }, command: { type: 'string', description: '命令' } }, required: ['terminalId', 'command'] } } },
    awaitTerminalCommand: { type: 'function', function: { name: 'awaitTerminalCommand', description: '在终端执行命令并等待完成', parameters: { type: 'object', properties: { terminalId: { type: 'number', description: '终端ID' }, command: { type: 'string', description: '命令' } }, required: ['terminalId', 'command'] } } },
    killTerminal: { type: 'function', function: { name: 'killTerminal', description: '关闭终端', parameters: { type: 'object', properties: { terminalId: { type: 'number', description: '终端ID' } }, required: ['terminalId'] } } },
    readClipboard: { type: 'function', function: { name: 'readClipboard', description: '读取剪贴板内容', parameters: { type: 'object', properties: {}, required: [] } } },
    writeClipboard: { type: 'function', function: { name: 'writeClipboard', description: '写入剪贴板', parameters: { type: 'object', properties: { text: { type: 'string', description: '内容' } }, required: ['text'] } } },
    takeScreenshot: { type: 'function', function: { name: 'takeScreenshot', description: '截取屏幕截图', parameters: { type: 'object', properties: {}, required: [] } } },
    extractTextFromImage: { type: 'function', function: { name: 'extractTextFromImage', description: '从图片中提取文字(OCR)', parameters: { type: 'object', properties: { imagePath: { type: 'string', description: '图片路径' } }, required: ['imagePath'] } } },
    getSystemInfo: { type: 'function', function: { name: 'getSystemInfo', description: '获取系统信息', parameters: { type: 'object', properties: {}, required: [] } } },
    getNetworkStatus: { type: 'function', function: { name: 'getNetworkStatus', description: '获取网络状态', parameters: { type: 'object', properties: {}, required: [] } } },
    openBrowser: { type: 'function', function: { name: 'openBrowser', description: '打开浏览器访问URL', parameters: { type: 'object', properties: { url: { type: 'string', description: 'URL地址' } }, required: ['url'] } } },
    openFileExplorer: { type: 'function', function: { name: 'openFileExplorer', description: '打开文件管理器', parameters: { type: 'object', properties: { path: { type: 'string', description: '路径' } }, required: ['path'] } } },
    manageContext: { type: 'function', function: { name: 'manageContext', description: '管理上下文信息,清理不需要的内容', parameters: { type: 'object', properties: { action: { type: 'string', enum: ['summarize', 'clear_old', 'clear_tool_results', 'keep_essential'], description: '操作类型' }, keepLast: { type: 'number', description: '保留最近N条消息' } }, required: ['action'] } } },
    autoSummarizeContext: { type: 'function', function: { name: 'autoSummarizeContext', description: '使用LLM自动总结当前上下文并覆盖', parameters: { type: 'object', properties: {}, required: [] } } },
    listSkills: { type: 'function', function: { name: 'listSkills', description: '列出所有技能，返回结果中ok字段表示是否成功，skills字段包含技能列表', parameters: { type: 'object', properties: {}, required: [] } } },
    makeSkill: { type: 'function', function: { name: 'makeSkill', description: '创建新技能，返回结果中ok字段表示是否成功', parameters: { type: 'object', properties: { name: { type: 'string', description: '技能名称' }, description: { type: 'string', description: '技能描述' }, prompt: { type: 'string', description: '系统提示词' } }, required: ['name', 'description', 'prompt'] } } },
    updateSkill: { type: 'function', function: { name: 'updateSkill', description: '更新已有技能，返回结果中ok字段表示是否成功', parameters: { type: 'object', properties: { id: { type: 'number', description: '技能ID' }, name: { type: 'string', description: '技能名称' }, description: { type: 'string', description: '技能描述' }, prompt: { type: 'string', description: '系统提示词' } }, required: ['id', 'name', 'description', 'prompt'] } } },
    initGeogebra: { type: 'function', function: { name: 'initGeogebra', description: '初始化Geogebra应用', parameters: { type: 'object', properties: { appName: { type: 'string', enum: ['classic'], description: '应用类型，默认classic' } }, required: [] } } },
    runGeogebraCommand: { type: 'function', function: { name: 'runGeogebraCommand', description: '执行Geogebra命令（Classic）。求解方程例：先f(x)=x^2-1，再Solve[f(x)=0]只需一个参数（方程）。求根例：Roots[f]得到点A,B,C，用x(A)提取值。', parameters: { type: 'object', properties: { command: { type: 'string', description: 'Geogebra Classic命令（注意Solve只取1参数，Roots返回点标签）' } }, required: ['command'] } } },
    getFunctionsFromGeogebra: { type: 'function', function: { name: 'getFunctionsFromGeogebra', description: '获取Geogebra函数列表', parameters: { type: 'object', properties: {}, required: [] } } },
    addFunctionToGeogebra: { type: 'function', function: { name: 'addFunctionToGeogebra', description: '添加函数/对象（Classic），例：f(x)=x^2-1 或 g: y=2x+1', parameters: { type: 'object', properties: { expression: { type: 'string', description: '函数表达式（Classic）' } }, required: ['expression'] } } },
    updateFunctionInGeogebra: { type: 'function', function: { name: 'updateFunctionInGeogebra', description: '更新函数（Classic），例：f(x)=x^3-1（直接重定义）', parameters: { type: 'object', properties: { name: { type: 'string', description: '函数名' }, expression: { type: 'string', description: '新表达式' } }, required: ['name', 'expression'] } } },
    deleteFunctionFromGeogebra: { type: 'function', function: { name: 'deleteFunctionFromGeogebra', description: '删除Geogebra函数', parameters: { type: 'object', properties: { name: { type: 'string', description: '函数名' } }, required: ['name'] } } },
    getCurrentGraphFromGeogebra: { type: 'function', function: { name: 'getCurrentGraphFromGeogebra', description: '获取当前Geogebra图形', parameters: { type: 'object', properties: {}, required: [] } } },
    getCurrentGraphDataFromGeogebra: { type: 'function', function: { name: 'getCurrentGraphDataFromGeogebra', description: '获取Geogebra图形数据', parameters: { type: 'object', properties: {}, required: [] } } },
    initCanvas: { type: 'function', function: { name: 'initCanvas', description: '初始化SVG画布', parameters: { type: 'object', properties: {}, required: [] } } },
    clearCanvas: { type: 'function', function: { name: 'clearCanvas', description: '清空画布所有对象', parameters: { type: 'object', properties: {}, required: [] } } },
    addCanvasObject: { type: 'function', function: { name: 'addCanvasObject', description: '添加SVG对象到画布。支持：rect(矩形)、circle(圆)、ellipse(椭圆)、line(直线)、polyline(折线)、polygon(多边形)、path(路径)、text(文本)', parameters: { type: 'object', properties: { type: { type: 'string', enum: ['rect', 'circle', 'ellipse', 'line', 'polyline', 'polygon', 'path', 'text'], description: 'SVG对象类型' }, id: { type: 'string', description: '对象ID（唯一标识）' }, attributes: { type: 'object', description: 'SVG属性，如{x:10,y:10,width:100,height:50,fill:"red",stroke:"black"}' } }, required: ['type', 'id', 'attributes'] } } },
    updateCanvasObject: { type: 'function', function: { name: 'updateCanvasObject', description: '更新画布对象属性', parameters: { type: 'object', properties: { id: { type: 'string', description: '对象ID' }, attributes: { type: 'object', description: '要更新的属性' } }, required: ['id', 'attributes'] } } },
    deleteCanvasObject: { type: 'function', function: { name: 'deleteCanvasObject', description: '删除画布对象', parameters: { type: 'object', properties: { id: { type: 'string', description: '对象ID' } }, required: ['id'] } } },
    exportCanvasSVG: { type: 'function', function: { name: 'exportCanvasSVG', description: '导出画布为SVG文件到工作区', parameters: { type: 'object', properties: { filename: { type: 'string', description: 'SVG文件名（默认canvas.svg）' } }, required: [] } } },
    askQuestions: { type: 'function', function: { name: 'askQuestions', description: '向用户提出问题收集信息，支持单选/多选/自由输入。返回{ok:true,answers:Array}', parameters: { type: 'object', properties: { questions: { type: 'array', items: { type: 'object', properties: { question: { type: 'string', description: '问题文本' }, options: { type: 'array', items: { type: 'string' }, description: '选项列表(可选,留空则为自由输入)' }, multiSelect: { type: 'boolean', description: '是否多选(仅当有options时有效)' } }, required: ['question'] }, description: '问题列表' } }, required: ['questions'] } } },
    downloadFile: { type: 'function', function: { name: 'downloadFile', description: '从互联网下载文件到工作区目录', parameters: { type: 'object', properties: { url: { type: 'string', description: '文件URL' }, filename: { type: 'string', description: '保存的文件名(可选,默认从URL提取)' } }, required: ['url'] } } }
  };

  return Object.keys(schemas)
    .filter(name => !enabledTools || enabledTools[name] !== false)
    .map(name => schemas[name]);
}
