/* SPDX-License-Identifier: GPL-3.0-or-later */
'use strict';
module.exports = {
  en: {
    'ui.tui.cmd.usage': 'Show tokens, spending and subscription quotas',
    'ui.tui.cmd.mouse': 'Toggle mouse capture (saved)',
    'ui.tui.args.mouse': '[on|off]',
    'ui.tui.mouseUsage': 'Usage: /mouse [on|off]',
    'ui.tui.mouseOn':
      'Mouse enabled: click menus, position the cursor, scroll and drag to copy; hold Shift for terminal selection',
    'ui.tui.mouseOff': 'Mouse capture disabled: use terminal selection, copy and paste',
    'ui.tui.usageTitle': 'Usage and quotas',
    'ui.tui.usageSessionCost': 'Session API spending: {cost}',
    'ui.tui.usageLoading': 'Loading quotas…',
    'ui.tui.usageUnavailable': 'Usage unavailable',
    'ui.tui.usagePeriod.5hour': '5-hour limit',
    'ui.tui.usagePeriod.weekly': 'Weekly limit',
    'ui.tui.usagePeriod.monthly': 'Monthly limit',
    'ui.tui.usagePeriod.other': 'Quota',
    'ui.tui.usageReset': 'Resets: {time}',
    'ui.tui.cmd.minimal': 'Toggle Minimal mode (saved per conversation)',
    'ui.tui.args.minimal': '[on|off]',
    'ui.tui.minimalUsage': 'Usage: /minimal [on|off]',
    'ui.tui.minimalBusy': 'Stop the current task before changing Minimal mode',
    'ui.tui.minimalBabe': 'Minimal mode is available in Chat and Code',
    'ui.tui.minimalOn': 'Minimal enabled: fixed prompt + shell / file editor',
    'ui.tui.minimalOff': 'Minimal disabled',
    'ui.tui.cmd.theme': 'Toggle following the GUI palette (saved)',
    'ui.tui.args.theme': '[on|off]',
    'ui.tui.themeUsage': 'Usage: /theme [on|off]',
    'ui.tui.themeGui': 'TUI theme: GUI palette',
    'ui.tui.themeTerminal': 'TUI theme: terminal defaults',
    'ui.tui.todoNav': '↑↓ select · Space / Enter toggle · Esc close',
    'ui.tui.retryTitle': 'LLM retry #{attempt}',
    'ui.tui.retryWait': 'Retry in {seconds}s · Esc stop',
    'ui.tui.retryRunning': 'Retrying · Esc stop',
    'ui.tui.notificationTitle': 'Notification',
    'ui.tui.configGroup.tui': 'TUI preferences',
    'ui.tui.customArgs': '[arguments]',
    'ui.tui.customCommand': 'Custom command',
    'ui.tui.unknownCommandHelp':
      'Unknown command /{name} (/help lists commands; /commands lists custom commands)',
    'ui.tui.cmd.undo': 'Stop and withdraw the last user message and its reply',
    'ui.tui.cmd.cwd': 'Open the current workspace in the system file manager',
    'ui.tui.cmd.config': 'Search and edit shared settings',
    'ui.tui.args.config': '[search]',
    'ui.tui.noDesktop': 'No graphical desktop is available; the file manager cannot be opened',
    'ui.tui.undone': 'Last message withdrawn; completed file changes remain on disk',
    'ui.tui.configBoolean': 'Enter true or false',
    'ui.tui.configNumber': 'Enter a valid number',
    'ui.tui.configTitle': 'Settings',
    'ui.tui.configHint': 'Type to search · ↑↓ select · Enter edit · Esc close',
    'ui.tui.configCount': '{count} settings · shared with GUI; fields save immediately',
    'ui.tui.configReadOnly': 'Managed by the runtime; read only',
    'ui.tui.configEditHint': 'Enter save · Esc back; JSON fields accept arrays and objects',
    'ui.tui.configSaved': 'Saved: {path}',
    'ui.tui.configRestart': 'Takes effect after restart',
    'ui.tui.searchHint':
      'Search {index}/{count} · Enter/F3 next · Shift+Enter/F3 previous · Esc back',
    'ui.tui.interrupt': 'Esc stop',
    'ui.tui.configGroup.llm': 'Model',
    'ui.tui.configGroup.theme': 'Appearance',
    'ui.tui.configGroup.runtime': 'Execution location',
    'ui.tui.configGroup.webResearch': 'Web search',
    'ui.tui.configGroup.budget': 'Usage and cost',
    'ui.tui.configGroup.voice': 'Voice',
    'ui.tui.configGroup.babe': 'Babe mode',
    'ui.tui.configGroup.decision': 'System One',
    'ui.tui.configGroup.tools': 'Tools',
    'ui.tui.configGroup.tarotVisible': 'Show destiny cards',
    'ui.tui.configGroup.language': 'Language',
  },
  de: {
    'ui.tui.cmd.usage': 'Tokens, Kosten und Abonnementkontingente anzeigen',
    'ui.tui.cmd.mouse': 'Maussteuerung umschalten (gespeichert)',
    'ui.tui.args.mouse': '[on|off]',
    'ui.tui.mouseUsage': 'Verwendung: /mouse [on|off]',
    'ui.tui.mouseOn':
      'Maus aktiviert: Menüs anklicken, Cursor setzen, scrollen und Text zum Kopieren auswählen; Umschalt für Terminalauswahl',
    'ui.tui.mouseOff':
      'Maussteuerung deaktiviert: native Terminalauswahl, Kopieren und Einfügen verwenden',
    'ui.tui.usageTitle': 'Nutzung und Kontingente',
    'ui.tui.usageSessionCost': 'API-Kosten dieser Sitzung: {cost}',
    'ui.tui.usageLoading': 'Kontingente werden geladen…',
    'ui.tui.usageUnavailable': 'Kontingent nicht verfügbar',
    'ui.tui.usagePeriod.5hour': '5-Stunden-Limit',
    'ui.tui.usagePeriod.weekly': 'Wochenlimit',
    'ui.tui.usagePeriod.monthly': 'Monatslimit',
    'ui.tui.usagePeriod.other': 'Kontingent',
    'ui.tui.usageReset': 'Zurücksetzung: {time}',
    'ui.tui.cmd.minimal': 'Minimal-Modus umschalten (pro Unterhaltung gespeichert)',
    'ui.tui.args.minimal': '[on|off]',
    'ui.tui.minimalUsage': 'Verwendung: /minimal [on|off]',
    'ui.tui.minimalBusy': 'Aktuelle Aufgabe vor dem Umschalten stoppen',
    'ui.tui.minimalBabe': 'Minimal ist in Chat und Code verfügbar',
    'ui.tui.minimalOn': 'Minimal aktiviert: fester Prompt + Shell / Dateieditor',
    'ui.tui.minimalOff': 'Minimal deaktiviert',
    'ui.tui.cmd.theme': 'GUI-Farben übernehmen oder Terminalfarben verwenden (gespeichert)',
    'ui.tui.args.theme': '[on|off]',
    'ui.tui.themeUsage': 'Verwendung: /theme [on|off]',
    'ui.tui.themeGui': 'TUI-Thema: GUI-Farben',
    'ui.tui.themeTerminal': 'TUI-Thema: Terminalfarben',
    'ui.tui.todoNav': '↑↓ auswählen · Leertaste / Enter umschalten · Esc schließen',
    'ui.tui.retryTitle': 'LLM-Wiederholung #{attempt}',
    'ui.tui.retryWait': 'Erneut in {seconds}s · Esc stoppen',
    'ui.tui.retryRunning': 'Wird erneut versucht · Esc stoppen',
    'ui.tui.notificationTitle': 'Benachrichtigung',
    'ui.tui.configGroup.tui': 'TUI-Einstellungen',
    'ui.tui.customArgs': '[Argumente]',
    'ui.tui.customCommand': 'Eigener Befehl',
    'ui.tui.unknownCommandHelp':
      'Unbekannter Befehl /{name} (/help zeigt Befehle; /commands zeigt eigene Befehle)',
    'ui.tui.cmd.undo': 'Stoppen und letzte Benutzernachricht samt Antwort zurücknehmen',
    'ui.tui.cmd.cwd': 'Aktuellen Arbeitsbereich im Dateimanager öffnen',
    'ui.tui.cmd.config': 'Gemeinsame Einstellungen suchen und bearbeiten',
    'ui.tui.args.config': '[Suche]',
    'ui.tui.noDesktop':
      'Kein grafischer Desktop verfügbar; der Dateimanager kann nicht geöffnet werden',
    'ui.tui.undone':
      'Letzte Nachricht zurückgenommen; bereits ausgeführte Dateiänderungen bleiben erhalten',
    'ui.tui.configBoolean': 'true oder false eingeben',
    'ui.tui.configNumber': 'Eine gültige Zahl eingeben',
    'ui.tui.configTitle': 'Einstellungen',
    'ui.tui.configHint': 'Tippen zum Suchen · ↑↓ auswählen · Enter bearbeiten · Esc schließen',
    'ui.tui.configCount':
      '{count} Einstellungen · gemeinsam mit der GUI; Felder werden sofort gespeichert',
    'ui.tui.configReadOnly': 'Von der Laufzeit verwaltet; schreibgeschützt',
    'ui.tui.configEditHint':
      'Enter speichern · Esc zurück; JSON-Felder erlauben Arrays und Objekte',
    'ui.tui.configSaved': 'Gespeichert: {path}',
    'ui.tui.configRestart': 'Wirksam nach dem Neustart',
    'ui.tui.searchHint':
      'Suche {index}/{count} · Enter/F3 weiter · Shift+Enter/F3 zurück · Esc zurück',
    'ui.tui.interrupt': 'Esc stoppen',
    'ui.tui.configGroup.llm': 'Modell',
    'ui.tui.configGroup.theme': 'Darstellung',
    'ui.tui.configGroup.runtime': 'Ausführungsort',
    'ui.tui.configGroup.webResearch': 'Websuche',
    'ui.tui.configGroup.budget': 'Nutzung und Kosten',
    'ui.tui.configGroup.voice': 'Spracheingabe',
    'ui.tui.configGroup.babe': 'Babe-Modus',
    'ui.tui.configGroup.decision': 'System One',
    'ui.tui.configGroup.tools': 'Tools',
    'ui.tui.configGroup.tarotVisible': 'Schicksalskarten anzeigen',
    'ui.tui.configGroup.language': 'Sprache',
  },
};

Object.assign(module.exports.en, {
  'ui.update.download': 'Download update',
  'ui.update.install': 'Restart to install',
  'ui.update.later': 'Later',
  'ui.update.confirm': 'Restart to install the update?',
  'ui.update.started': 'Checking and downloading an update; you will be notified when it is ready',
  'ui.update.ready': 'Update downloaded and verified. Restart to install (/update install)',
  'ui.update.current': 'Already up to date',
  'ui.update.error': 'Update failed: ',
  'ui.update.downloading': 'Downloading update',
  'ui.update.checking': 'Checking for updates',
  'ui.tui.cmd.update': 'Download an update; restart to install when ready',
  'ui.tui.args.update': '[install]',
  'ui.tui.configNavigation': 'Type to search · ↑↓ select · Enter open or edit · Esc back',
  'ui.tui.configOn': 'On',
  'ui.tui.configOff': 'Off',
  'ui.tui.configItems': '{count} items',
  'ui.tui.configAdd': '+ Add item',
  'ui.tui.configDelete': 'Delete this item',
  'ui.tui.configShared': 'Shared with GUI / WebUI; changes save immediately',
  'ui.webui.start': 'Start WebUI',
  'ui.webui.stop': 'Stop WebUI',
  'ui.webui.running': 'Running: {url}',
  'ui.webui.stopped': 'WebUI is stopped; backend sessions can keep running',
  'ui.webui.backendStatus': 'Backend PID {pid} · {clients} browser / Remote connections',
  'ui.webui.passwordFailed': 'Could not save the password',
  'ui.webui.invalidPort': 'Port must be an integer from 1024 to 65535',
  'ui.webui.needTotp': 'Generate and verify a TOTP secret first',
  'ui.webui.applying': 'Applying…',
  'ui.webui.verified': 'Verified',
  'ui.webui.invalidCode': 'Incorrect verification code',
  'ui.tor.hint':
    'Connect the native mobile App through a Tor onion service using the WebUI password and two-step verification. No public ports are required.',
  'ui.tor.auto': 'Connect Tor automatically with the backend',
  'ui.tor.useBridges': 'Use bridges',
  'ui.tor.bridges': 'Bridge configuration (one per line)',
  'ui.tor.start': 'Connect Tor',
  'ui.tor.stop': 'Stop Tor',
  'ui.tor.getBridges': 'Get bridges',
  'ui.tor.stopped': 'Tor disconnected',
  'ui.tor.preparing': 'Preparing Tor',
  'ui.tor.connecting': 'Connecting Tor',
  'ui.tor.ready': 'Tor connected',
  'ui.tor.error': 'Tor connection failed',
});

Object.assign(module.exports.de, {
  'ui.update.download': 'Update herunterladen',
  'ui.update.install': 'Zum Installieren neu starten',
  'ui.update.later': 'Später',
  'ui.update.confirm': 'Zum Installieren des Updates neu starten?',
  'ui.update.started':
    'Update wird gesucht und heruntergeladen; danach erscheint eine Neustartmeldung',
  'ui.update.ready':
    'Update heruntergeladen und geprüft. Zum Installieren neu starten (/update install)',
  'ui.update.current': 'Bereits aktuell',
  'ui.update.error': 'Update fehlgeschlagen: ',
  'ui.update.downloading': 'Update wird heruntergeladen',
  'ui.update.checking': 'Suche nach Updates',
  'ui.tui.cmd.update': 'Update herunterladen; danach zum Installieren neu starten',
  'ui.tui.args.update': '[install]',
  'ui.tui.configNavigation': 'Suchen · ↑↓ wählen · Enter öffnen oder bearbeiten · Esc zurück',
  'ui.tui.configOn': 'Ein',
  'ui.tui.configOff': 'Aus',
  'ui.tui.configItems': '{count} Einträge',
  'ui.tui.configAdd': '+ Eintrag hinzufügen',
  'ui.tui.configDelete': 'Diesen Eintrag löschen',
  'ui.tui.configShared': 'Gemeinsam mit GUI / WebUI; Änderungen werden sofort gespeichert',
  'ui.webui.start': 'WebUI starten',
  'ui.webui.stop': 'WebUI stoppen',
  'ui.webui.running': 'Aktiv: {url}',
  'ui.webui.stopped': 'WebUI ist gestoppt; Hintergrundsitzungen können weiterlaufen',
  'ui.webui.backendStatus': 'Backend-PID {pid} · {clients} Browser- / Remote-Verbindungen',
  'ui.webui.passwordFailed': 'Passwort konnte nicht gespeichert werden',
  'ui.webui.invalidPort': 'Der Port muss eine ganze Zahl zwischen 1024 und 65535 sein',
  'ui.webui.needTotp': 'Zuerst einen TOTP-Schlüssel erstellen und prüfen',
  'ui.webui.applying': 'Wird angewendet…',
  'ui.webui.verified': 'Bestätigt',
  'ui.webui.invalidCode': 'Falscher Bestätigungscode',
  'ui.tor.hint':
    'Die native Mobil-App über einen Tor-Onion-Dienst mit WebUI-Passwort und Zwei-Faktor-Verifizierung verbinden. Keine öffentlichen Ports erforderlich.',
  'ui.tor.auto': 'Tor beim Backend-Start automatisch verbinden',
  'ui.tor.useBridges': 'Brücken verwenden',
  'ui.tor.bridges': 'Brückenkonfiguration (eine pro Zeile)',
  'ui.tor.start': 'Tor verbinden',
  'ui.tor.stop': 'Tor stoppen',
  'ui.tor.getBridges': 'Brücken abrufen',
  'ui.tor.stopped': 'Tor getrennt',
  'ui.tor.preparing': 'Tor wird vorbereitet',
  'ui.tor.connecting': 'Tor wird verbunden',
  'ui.tor.ready': 'Tor verbunden',
  'ui.tor.error': 'Tor-Verbindung fehlgeschlagen',
});

Object.assign(module.exports.en, {
  'ui.update.installing': 'Exiting to install the update',
  'ui.update.launcherReady':
    'Update downloaded and verified. Run /update install to exit, then run your original launch command to use the new version.',
  'ui.update.launcherConfirm':
    'Exit the shared backend? Run your original launch command again to use the downloaded update.',
});

Object.assign(module.exports.de, {
  'ui.update.installing': 'Die App wird für die Installation beendet',
  'ui.update.launcherReady':
    'Update heruntergeladen und geprüft. Mit /update install beenden und danach den bisherigen Startbefehl ausführen, um die neue Version zu nutzen.',
  'ui.update.launcherConfirm':
    'Das gemeinsame Backend beenden? Danach den bisherigen Startbefehl ausführen, um das heruntergeladene Update zu nutzen.',
});
