/* SPDX-License-Identifier: GPL-3.0-or-later */
'use strict';
// Static imports let the guest bundle expose exactly the same SDK identities as
// its plugin kernel. Plugins do not get a second copy of Cordis or scope symbols.
module.exports = {
  cordis: require('@deepseek-ai/cordis'),
  schemastery: require('@deepseek-ai/schemastery'),
  'dsh-tools': require('./shims/dsh-tools'),
  'dsh-llm': require('@deepseek-ai/dsh-llm'),
  'dsh-brand': require('@deepseek-ai/dsh-brand'),
  'dsh-util-values': require('@deepseek-ai/dsh-util-values'),
  'dsh-scope': require('@deepseek-ai/dsh-scope'),
  'dsh-agent': require('@deepseek-ai/dsh-agent'),
  'dsh-session': require('@deepseek-ai/dsh-session'),
  'dsh-session-projection': require('@deepseek-ai/dsh-session-projection'),
  'dsh-session-query': require('@deepseek-ai/dsh-session-query'),
  'dsh-workspace': require('@deepseek-ai/dsh-workspace'),
  'dsh-persona': require('@deepseek-ai/dsh-persona'),
  'dsh-agent-default-model': require('@deepseek-ai/dsh-agent-default-model'),
  'dsh-session-persistence': require('@deepseek-ai/dsh-session-persistence'),
  'dsh-fs': require('@deepseek-ai/dsh-fs'),
  'dsh-shell-env': require('@deepseek-ai/dsh-shell-env'),
  'dsh-attachment': require('@deepseek-ai/dsh-attachment'),
  'dsh-lsp': require('@deepseek-ai/dsh-lsp'),
  'dsh-token-meter': require('@deepseek-ai/dsh-token-meter'),
  'dsh-shell': require('@deepseek-ai/dsh-shell'),
  'dsh-subprocess': require('@deepseek-ai/dsh-subprocess'),
  'dsh-system-prompt': require('@deepseek-ai/dsh-system-prompt'),
  'dsh-skill': require('@deepseek-ai/dsh-skill'),
  'dsh-storage': require('@deepseek-ai/dsh-storage'),
  'dsh-storage-domain': require('@deepseek-ai/dsh-storage-domain'),
  'dsh-jobs': require('@deepseek-ai/dsh-jobs'),
  'dsh-web': require('@deepseek-ai/dsh-web'),
  'dsh-subagent': require('@deepseek-ai/dsh-subagent'),
  'dsh-compaction': require('@deepseek-ai/dsh-compaction'),
  'dsh-terminal': require('@deepseek-ai/dsh-terminal'),
  'dsh-commands': require('@deepseek-ai/dsh-commands'),
  'dsh-user-approval': require('@deepseek-ai/dsh-user-approval'),
  'dsh-user-questions': require('@deepseek-ai/dsh-user-questions'),
  'dsh-sandbox': require('@deepseek-ai/dsh-sandbox'),
  'dsh-sandbox-policy': require('@deepseek-ai/dsh-sandbox-policy'),
};
